name: AI Patch PR
on:
  workflow_dispatch:
    inputs:
      patch_b64:
        description: Base64-encoded unified diff (output of `git diff -u` or `git format-patch` content)
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Decode patch
        run: |
          echo "${{ github.event.inputs.patch_b64 }}" | base64 -d > changes.patch
          wc -l changes.patch

      - name: Apply patch
        run: |
          git config user.name "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"
          # Fail early if patch can't be applied
          git apply --index --whitespace=fix changes.patch
          git commit -m "AI patch via workflow ${{ github.run_id }}"

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ai/patch-${{ github.run_id }}
          commit-message: "AI patch"
          title: "AI patch"
          body: |
            Generated by AI. Please review carefully.
          signoff: false
          delete-branch: true
